### ISSUE TITLE
Undo changes causes an InvalidOperationException in InMemory db provider

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#537]
Calling `GenericContent.UndoCheckOut` causes an exception in InMemory db provider sometimes:

```txt
Collection was modified; enumeration operation may not execute.
```

Maybe a lock would solve the problem.

```txt
Message: Error during undo changes of /Root/b1ba03b6-010b-42ee-aaeb-cc1329b70085/aa21cc8c-b512-4ac2-a1c9-90d119f61811/418e0ebe-a8a8-4b95-8a66-45dcfb8aec2b (v: V1.0.A): Collection was modified; enumeration operation may not execute.
```

Call stack

```txt
InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at SenseNet.Tests.Implementations.InMemoryDataProvider.SetLastVersionSlots(Database db, Int32 nodeId, Int32& lastMajorVersionId, Int32& lastMinorVersionId, Int64& nodeTimeStamp) in D:\Dev\github\sensenet\src\Tests\SenseNet.Tests\Implementations\InMemoryDataProvider.cs:line 1206
   at SenseNet.Tests.Implementations.InMemoryDataProvider.DeleteVersion(Int32 versionId, NodeData nodeData, Int32& lastMajorVersionId, Int32& lastMinorVersionId) in D:\Dev\github\sensenet\src\Tests\SenseNet.Tests\Implementations\InMemoryDataProvider.cs:line 580
   at SenseNet.ContentRepository.Storage.Data.DataProvider.SaveNodeData(NodeData nodeData, NodeSaveSettings settings, Int32& lastMajorVersionId, Int32& lastMinorVersionId) in D:\Dev\github\sensenet\src\Storage\Data\DataProvider.cs:line 139
   at SenseNet.ContentRepository.Storage.DataBackingStore.SaveNodeDataTransactional(Node node, NodeSaveSettings settings, IIndexPopulator populator, String originalPath, String newPath) in D:\Dev\github\sensenet\src\Storage\DataBackingStore.cs:line 616
   at SenseNet.ContentRepository.Storage.DataBackingStore.SaveNodeData(Node node, NodeSaveSettings settings, IIndexPopulator populator, String originalPath, String newPath) in D:\Dev\github\sensenet\src\Storage\DataBackingStore.cs:line 457
   at SenseNet.ContentRepository.Storage.Node.Save(NodeSaveSettings settings) in D:\Dev\github\sensenet\src\Storage\Node.cs:line 2659
   at SenseNet.ContentRepository.GenericContent.Save(NodeSaveSettings settings) in D:\Dev\github\sensenet\src\ContentRepository\GenericContent.cs:line 1740
   at SenseNet.ContentRepository.FileBase.Save(NodeSaveSettings settings) in D:\Dev\github\sensenet\src\ContentRepository\FileBase.cs:line 69
   at SenseNet.ContentRepository.SavingAction.Execute() in D:\Dev\github\sensenet\src\ContentRepository\SavingAction.cs:line 427
   at SenseNet.ContentRepository.GenericContent.UndoCheckOut(Boolean forceRefresh) in D:\Dev\github\sensenet\src\ContentRepository\GenericContent.cs:line 1862
   at SenseNet.ContentRepository.GenericContent.UndoCheckOut() in D:\Dev\github\sensenet\src\ContentRepository\GenericContent.cs:line 1844
   at SenseNet.Packaging.Steps.Internal.UndoChanges.<>c__DisplayClass9_0.<UndoContentChanges>b__1(GenericContent gc) in D:\Dev\github\sensenet\src\ContentRepository\Packaging\Steps\Internal\UndoChanges.cs:line 56
```

**Comment by tusmester** [comment]
closed as fixed
