### ISSUE TITLE
Install sensenet Content Repository database - problem

### ISSUE THREAD

**Issue by avukomanovic** [SenseNet/sensenet#540]
I have tried to install sensenet Content Repository database several times, but have this kind of error:

Starting Repository...

ApplicationException: Phase terminated with error: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.
   at SenseNet.Packaging.PackageManager.ExecuteCurrentPhase(Manifest manifest, ExecutionContext executionContext) in D:\Dev\github\sensenet\src\ContentRepository\Packaging\PackageManager.cs:line 165
   at SenseNet.Packaging.PackageManager.Execute(String packagePath, String targetPath, Int32 currentPhase, String[] parameters, TextWriter console) in D:\Dev\github\sensenet\src\ContentRepository\Packaging\PackageManager.cs:line 71
   at SenseNet.Tools.SnAdmin.SnAdminRuntime.ExecutePhase(String packagePath, String targetDirectory, Int32 phase, String[] parameters, String logFilePath, Boolean help, Boolean schema) in D:\Dev\github\sensenet\src\Tools\SnAdminRuntime\SnAdminRuntime.cs:line 191
---- Inner Exception:
SecurityException: The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.
   at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source)
   at SenseNet.Diagnostics.SnEventLogger..ctor(String logName, String logSourceName)
   at SenseNet.Configuration.Providers.<>c.<.ctor>b__153_0() in D:\Dev\github\sensenet\src\Storage\Configuration\Providers.cs:line 83
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SenseNet.ContentRepository.RepositoryInstance.InitializeLogger() in D:\Dev\github\sensenet\src\ContentRepository\RepositoryInstance.cs:line 350
   at SenseNet.ContentRepository.RepositoryInstance.DoStart() in D:\Dev\github\sensenet\src\ContentRepository\RepositoryInstance.cs:line 130
   at SenseNet.ContentRepository.RepositoryInstance.Start(RepositoryStartSettings settings) in D:\Dev\github\sensenet\src\ContentRepository\RepositoryInstance.cs:line 107
   at SenseNet.ContentRepository.Repository.Start(RepositoryStartSettings settings) in D:\Dev\github\sensenet\src\ContentRepository\Repository.cs:line 55
   at SenseNet.Packaging.Steps.StartRepository.Execute(ExecutionContext context) in D:\Dev\github\sensenet\src\ContentRepository\Packaging\Steps\StartRepository.cs:line 55
   at SenseNet.Packaging.PackageManager.ExecuteCurrentPhase(Manifest manifest, ExecutionContext executionContext) in D:\Dev\github\sensenet\src\ContentRepository\Packaging\PackageManager.cs:line 112

Any solution? I'm using SQL Server Express 2017

**Comment by tusmester** [comment]
My guess is that the user who executes the application does not have enough **permissions for the Windows registry** (where these Event logs are registered). The quickest way to solve this is to switch to an admin user who has enough permissions. An alternative is to configure a *different logger*: one that does not want to write to the Event Log. There is a built-in logger that writes entries to the file system instead: `SnFileSystemEventLogger`.

If you encounter this during the install process, please configure the logger in the `web\Tools\SnAdminRuntime.exe.config` file:

```xml
<sensenet>
   <providers>
      <add key="EventLogger" value="SenseNet.Diagnostics.SnFileSystemEventLogger" />
   </providers>
</sensenet>
```

If you encounter this in your web application, there is a way to configure the logger *from code* instead of the config file (of course you may do the same in the web.config too):

https://stackoverflow.com/questions/53069775/asp-net-mvc-securityexception-the-source-was-not-found-but-some-or-all-event

More details about logging:

https://community.sensenet.com/docs/logging/

**Comment by LuisAverhoff** [comment]
@avukomanovic I'm assuming you created the repository on your local machine, web deployed it to virtual machine o via some other service(aws, gcp etc) and ran into this error because normally when you run snAdmin and it runs to completion, it by defaults creates a registry key called Sensenet in your eventlog folder. So if you are running this on virtual machine and don't plan on deploying to other machines as well, you can simply connect remotely to your virtual machine and create the registry key there. Not the best solution but it is something.

**Comment by kultsar** [comment]
@avukomanovic, we are closing this issue, but please feel free to reopen.
