### ISSUE TITLE
snadmin install-services error : Unknown property name : İtem

### ISSUE THREAD

**Issue by musayilmazx** [SenseNet/sensenet#623]
The below command:
.\snadmin install-services dataSource:.\SENSE initialCatalog:sensenet ForcedReinstall:true
erros out with the following error:

ApplicationException: Phase terminated with error: Unknown property. Step: SenseNet.Packaging.Steps.ForEach, name: İtem.
   at SenseNet.Packaging.PackageManager.ExecuteCurrentPhase(Manifest manifest, ExecutionContext executionContext)
   at SenseNet.Packaging.PackageManager.Execute(String packagePath, String targetPath, Int32 currentPhase, String[] parameters, TextWriter console)
   at SenseNet.Tools.SnAdmin.SnAdminRuntime.ExecutePhase(String packagePath, String targetDirectory, Int32 phase, String[] parameters, String logFilePath, Boolean help, Boolean schema)
---- Inner Exception:
InvalidPackageException: Unknown property. Step: SenseNet.Packaging.Steps.ForEach, name: İtem.
   at SenseNet.Packaging.Steps.Step.GetProperty(String name)
   at SenseNet.Packaging.Steps.Step.SetProperty(String name, XmlNode value, ExecutionContext executionContext)
   at SenseNet.Packaging.Steps.Step.BuildStep(Int32 stepId, String stepName, Dictionary`2 parameters, ExecutionContext executionContext)
   at SenseNet.Packaging.PackageManager.ExecuteCurrentPhase(Manifest manifest, ExecutionContext executionContext)

**Comment by sreekanthedayar** [comment]
I came accross a strange error, dont know if it is bug, just posting for your info. Installed in visual studio 2019 and SQL Server 2019 and i was having no problem at all. But in production i am using SQL server 2014. Tried to install everything from fresh using visual studio 2019 and SQL Server 2014. While installing DB error came and stopped.
**Details of error on installation:**
ApplicationException: Phase terminated with error: A database exception occured during execution of the operation. See InnerException for details.
   at SenseNet.Packaging.PackageManager.ExecuteCurrentPhase(Manifest manifest, ExecutionContext executionContext)
   at SenseNet.Packaging.PackageManager.Execute(String packagePath, String targetPath, Int32 currentPhase, PackageParameter[] parameters, TextWriter console, RepositoryBuilder builder, Boolean editConnectionString)
   at SenseNet.Tools.SnAdmin.Testability.BuiltInPackageManagerWrapper.Execute(String packagePath, String targetDirectory, Int32 phase, String[] parameters, TextWriter output) in E:\BuildAgent\_work\63\s\src\Tools\SnAdminRuntime\Testability\PackageManagerWrapper.cs:line 27
   at SenseNet.Tools.SnAdmin.SnAdminRuntime.ExecutePhase(String packagePath, String targetDirectory, Int32 phase, String[] parameters, String logFilePath, Boolean help, Boolean schema) in E:\BuildAgent\_work\63\s\src\Tools\SnAdminRuntime\SnAdminRuntime.cs:line 192
---- Inner Exception:
DataException: A database exception occured during execution of the operation. See InnerException for details.
   at SenseNet.ContentRepository.Storage.Data.DataStore.<LoadNodesAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SenseNet.ContentRepository.Storage.Data.DataStore.<LoadNodeAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SenseNet.ContentRepository.Storage.Node.LoadNode(NodeHead head, VersionNumber version)
   at SenseNet.ContentRepository.Storage.Node.LoadNode(Int32 nodeId, VersionNumber version)
   at SenseNet.ContentRepository.Repository.<>c.<Start>b__1_0()
   at SenseNet.ContentRepository.Storage.Security.SystemAccount.Execute[T](Func`1 function)
   at SenseNet.ContentRepository.Repository.Start(RepositoryStartSettings settings)
   at SenseNet.Packaging.Steps.StartRepository.Execute(ExecutionContext context)
   at SenseNet.Packaging.PackageManager.ExecuteCurrentPhase(Manifest manifest, ExecutionContext executionContext)
---- Inner Exception:
SqlException: Invalid object name 'STRING_SPLIT'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SenseNet.ContentRepository.Storage.Data.SnDataContext.<ExecuteReaderAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SenseNet.ContentRepository.Storage.Data.RelationalDataProviderBase.<LoadNodesAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SenseNet.ContentRepository.Storage.Data.DataStore.<LoadNodesAsync>d__23.MoveNext()

**Comment by herflis** [comment]
Hi @sreekanthedayar,
only SQL Server 2016 and above versions are supported.

**Comment by sreekanthedayar** [comment]
Oh I See, never say it anywhere in the documents or site, request to add this. I had missed this. any work around?
